# Generated by Django 4.1.1 on 2022-10-16 10:47

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(help_text="Fullname", max_length=255)),
                ("email", models.EmailField(help_text="Email", max_length=254)),
                ("phone", models.CharField(help_text="Phone number", max_length=20)),
                (
                    "quest",
                    models.CharField(
                        blank=True,
                        help_text="User request",
                        max_length=50000,
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Additional file",
                        null=True,
                        upload_to=contacts.models.contact_files,
                    ),
                ),
            ],
        ),
    ]
