# Generated by Django 4.1.1 on 2022-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="quest",
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.CharField(
                blank=True, help_text="Message", max_length=50000, null=True
            ),
        ),
    ]
