# Generated by Django 4.1.1 on 2022-10-16 12:09

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_remove_contact_quest_contact_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(help_text="Fullname", max_length=255)),
                ("email", models.EmailField(help_text="Email", max_length=254)),
                ("phone", models.CharField(help_text="Phone number", max_length=20)),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="Message", max_length=50000, null=True
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Additional file",
                        null=True,
                        upload_to=contacts.models.contact_files,
                    ),
                ),
                (
                    "received",
                    models.DateTimeField(
                        auto_now=True, help_text="Date message was received"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
