# Generated by Django 4.1.1 on 2022-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_message_delete_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(
                blank=True, help_text="Message", max_length=50000, null=True
            ),
        ),
    ]
