# Generated by Django 4.1.1 on 2022-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_message_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hiring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(help_text="Fullname", max_length=255)),
                ("email", models.EmailField(help_text="Email", max_length=254)),
                ("phone", models.CharField(help_text="Phone number", max_length=20)),
                (
                    "project_title",
                    models.CharField(help_text="Project title", max_length=255),
                ),
                (
                    "education_level",
                    models.CharField(help_text="Education level", max_length=50),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department/Project format",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "received",
                    models.DateTimeField(
                        auto_now=True, help_text="Date request was received"
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, help_text="Attended status"),
                ),
            ],
            options={
                "verbose_name_plural": "Hirings",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="attended",
            field=models.BooleanField(default=False, help_text="Attended status"),
        ),
    ]
