# Generated by Django 4.1.1 on 2022-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_hiring_message_attended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hiring",
            name="received",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date request was received"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="received",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date message was received"
            ),
        ),
    ]
