# Generated by Django 4.1.1 on 2022-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_hiring_received_alter_message_received"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Subscriber email", max_length=254),
                ),
                (
                    "joined",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Subscribed date"
                    ),
                ),
            ],
        ),
    ]
