# Generated by Django 4.1.1 on 2022-09-28 07:36

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Department name', max_length=60)),
                ('image_id', models.CharField(default=None, help_text='Unsplash image ID', max_length=15, verbose_name='Image ID')),
                ('description', models.TextField(default=None, help_text='Description', max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Topic title', max_length=155)),
                ('abstract', models.TextField(default=None, help_text='Project Abstract', max_length=3000)),
                ('file', models.FileField(blank=True, help_text='Project file', null=True, upload_to=projects.models.project_file)),
                ('pages', models.IntegerField(help_text='Number of pages')),
                ('price', models.CharField(help_text='Project price', max_length=55)),
                ('chapters', models.CharField(help_text='Number of chapters', max_length=55)),
                ('department', models.ForeignKey(help_text='Project topic department', on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
                ('tags', taggit.managers.TaggableManager(help_text='Related names to other projects', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
