# Generated by Django 4.1.1 on 2022-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "Departments"},
        ),
        migrations.RemoveField(
            model_name="topic",
            name="abstract",
        ),
        migrations.AddField(
            model_name="topic",
            name="brief",
            field=models.TextField(
                default=None, help_text="Project Abstract", max_length=10000
            ),
        ),
    ]
