# Generated by Django 4.1.1 on 2022-09-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_topic_brief"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="description",
        ),
    ]
