# Generated by Django 4.1.1 on 2022-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_department_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="extention",
            field=models.CharField(
                blank=True, default="", help_text="Format", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="brief",
            field=models.TextField(
                blank=True, help_text="Project Brief", max_length=10000, null=True
            ),
        ),
    ]
