# Generated by Django 4.1.1 on 2022-10-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name_plural": "Transactions"},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="files_sent",
        ),
        migrations.AddField(
            model_name="transaction",
            name="settled",
            field=models.BooleanField(default=False, help_text="Files has been sent"),
        ),
    ]
