# Generated by Django 4.1.1 on 2022-10-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="phone",
            field=models.CharField(
                default=None, help_text="Phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="first_name",
            field=models.CharField(default=None, help_text="First name", max_length=60),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="last_name",
            field=models.CharField(default=None, help_text="Last name", max_length=60),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="paid",
            field=models.CharField(
                default="0.00", help_text="Amount paid", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                default="", help_text="Transaction reference", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="topic",
            field=models.ForeignKey(
                help_text="Project topic",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="projects.topic",
            ),
        ),
    ]
