# Generated by Django 4.1.2 on 2022-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_transaction_occurred"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["title"], "verbose_name_plural": "Topics"},
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                default=None, help_text="Department name", max_length=155
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                default=None, help_text="Topic title", max_length=555
            ),
        ),
    ]
