# Generated by Django 4.1.2 on 2022-12-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paystack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Paystack",
            },
        ),
    ]
