# Generated by Django 4.1.1 on 2022-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asked",
            name="posted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
